//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Termin.Resources.Areas.Teacher.Pages.Shared {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _AddQuestionPartial {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _AddQuestionPartial() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Termin.Resources.Areas.Teacher.Pages.Shared._AddQuestionPartial", typeof(_AddQuestionPartial).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        public static string Add_Question {
            get {
                return ResourceManager.GetString("Add Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one option.
        /// </summary>
        public static string Choose_one_option {
            get {
                return ResourceManager.GetString("Choose one option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstOption.
        /// </summary>
        public static string FirstOption {
            get {
                return ResourceManager.GetString("FirstOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ForthOption.
        /// </summary>
        public static string ForthOption {
            get {
                return ResourceManager.GetString("ForthOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 1.
        /// </summary>
        public static string Option_1 {
            get {
                return ResourceManager.GetString("Option 1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2.
        /// </summary>
        public static string Option_2 {
            get {
                return ResourceManager.GetString("Option 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 3.
        /// </summary>
        public static string Option_3 {
            get {
                return ResourceManager.GetString("Option 3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 4.
        /// </summary>
        public static string Option_4 {
            get {
                return ResourceManager.GetString("Option 4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        public static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RighAnswer.
        /// </summary>
        public static string RighAnswer {
            get {
                return ResourceManager.GetString("RighAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecondOption.
        /// </summary>
        public static string SecondOption {
            get {
                return ResourceManager.GetString("SecondOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ThirdOption.
        /// </summary>
        public static string ThirdOption {
            get {
                return ResourceManager.GetString("ThirdOption", resourceCulture);
            }
        }
    }
}
